imports:
    - { resource: services.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Service\CurrencyExchangeRatesServiceInterface: '@App\Service\CurrencyExchangeRatesOfflineService'